import Head from "next/head";
import { useState, useDeferredValue, useCallback } from "react";
import { Button, InputAdornment, TextField } from "@mui/material";

export default function Home() {
  const [value, setValue] = useState("");
  const deferredValue = useDeferredValue(value);

  const handleChange = useCallback((e: any) => setValue(e.target.value), []);

  return (
    <>
      <Head>
        <title>GPT-free</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TextField
        multiline
        fullWidth
        value={value}
        onChange={handleChange}
        variant="standard"
        placeholder="Ask GPT-free"
        InputProps={{
          disableUnderline: true,
          endAdornment: (
            <InputAdornment position="end">
              <Button
        sx={{
          gap: 2,
          px: 2,
          background: "rgba(0,0,0,0.1)!important",
          textTransform: "none",
          borderRadius: 999,
          mr: 1,
          color: "#000",
          [`@media (prefers-color-scheme: dark)`]: {
            background: "rgba(255,255,255,.1)!important",
            color: "#fff",
          },
        }}
      >
        Send <span className="material-symbols-outlined">north</span>
      </Button>
      </InputAdornment>
          )
          sx: {
            p: 2,
            [`@media (prefers-color-scheme: dark)`]: {
              color: "#fff",
            },
          },
        }}
      />
    </>
  );
}
